### PR TITLE
Feature/subaccount

### PR DESCRIPTION
**Pull request by danstefancu**
Integrate subAccount option in bundle configuration too.

### CODE REVIEW

**Comment by danstefancu** [comment]
Hey @Kyoushu - any chance to merge this soon? The api key fails in travis

**Comment by Rattler3** [comment]
@danstefancu This has been merged, I will tag a release later today.

**Comment by danstefancu** [comment]
@Rattler3 Thank you :)

**Comment by Rattler3** [comment]
Thank you for your contribution!

**Pull request merged**
